name: Deploy the react app

on:
  push:
    branches: [ master ]

jobs:
  # Contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest # you can use windows and mac as well  
    steps:
      # Checks out repository, so job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "17.0.0"

      - name: installing NPM
        run: npm i

      - name: Building the project
        run: npm run build --if-present

      - name: Netlify Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod

